
name: Run Code Coverage Tests
on: workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: test
        run: gradle test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - name: jacoco
        run: gradle test jacocoTestReport
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
